# Generated by Django 3.2.5 on 2021-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField()),
                ('destination', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
